### 1 - You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy

def arrays(arr):
    result = numpy.array(arr, float)
    result = result[::-1]
    return result

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### 2 - You are given a space separated list of nine integers. Your task is to convert this list into a 3x3 NumPy array.

In [2]:
import numpy

arr = input().strip().split()
arr = numpy.array(arr, int)
arr.shape = (3, 3)
print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3 - You are given a NxM integer array matrix with space separated elements (N = rows and M = columns). Your task is to print the transpose and flatten results.

In [3]:
import numpy

arr = []
n, m = input().split()

for i in range(int(n)):
    arr.append(input().split())

arr = numpy.array(arr, int)
print(arr.T)
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


### 4 - You are given two integer arrays of size NxP and MxP (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [4]:
import numpy

n, m, p = input().split()
arr1 = []
arr2 = []

for i in range(int(n)):
    arr1.append(input().split())
    
for i in range(int(m)):
    arr2.append(input().split())
    
arr1 = numpy.array(arr1, int)
arr2 = numpy.array(arr2, int)

arr3 = numpy.concatenate((arr1, arr2))
print(arr3)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### 5 - You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [5]:
import numpy

size = tuple(map(int, input().split()))
print(numpy.zeros(size, dtype = numpy.int))
print(numpy.ones(size, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### 6 - Your task is to print an array of size NxM with its main diagonal elements as 1's and 0's everywhere else.

In [6]:
import numpy
numpy.set_printoptions(legacy='1.13')

n, m = map(int, input().split())
print(numpy.eye(n, m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 7 - You are given two integer arrays, A and B of dimensions NxM.
Your task is to perform the following operations:

- Add ( + )
- Subtract ( - )
- Multiply ( * )
- Integer Division ( / )
- Mod ( % )
- Power ( ** )

In [7]:
import numpy

n, m = input().split()
arr1 = []
arr2 = []

for i in range(int(n)):
    arr1.append(input().split())

for i in range(int(n)):
    arr2.append(input().split())
    
arr1 = numpy.array(arr1, int)
arr2 = numpy.array(arr2, int)

print(numpy.add(arr1, arr2))
print(numpy.subtract(arr1, arr2))
print(numpy.multiply(arr1, arr2))
print(numpy.floor_divide(arr1, arr2))
print(numpy.mod(arr1, arr2))
print(numpy.power(arr1, arr2))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


### 8 - You are given a 1-D array, A. Your task is to print the floor, ceil and rint of all the elements of A.

In [8]:
import numpy
numpy.set_printoptions(legacy='1.13')

arr1 = numpy.array(list(map(float, input().split())))

print(numpy.floor(arr1))
print(numpy.ceil(arr1))
print(numpy.rint(arr1))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### 9 - You are given a 2-D array with dimensions NxM. Your task is to perform the sum tool over axis 0 and then find the product of that result.

In [9]:
import numpy

n, m = input().split()
arr = []

for i in range(int(n)):
    arr.append(input().split())
    
arr = numpy.array(arr, int)
arr_sum = numpy.sum(arr, axis=0)
print(numpy.prod(arr_sum))

2 2
1 2
3 4
24


### 10 - You are given a 2-D array with dimensions NxM. Your task is to perform the min function over axis 1 and then find the max of that.

In [10]:
import numpy

n, m = input().split()
arr = []

for i in range(int(n)):
    arr.append(input().split())
    
arr = numpy.array(arr, int)
arr_min = numpy.min(arr, axis=1)
print(numpy.max(arr_min))

4 2
2 5
3 7
1 3
4 0
3


### 11 - You are given a 2-D array of size NxM.
Your task is to find:

- The mean along axis 1
- The var along axis 0
- The std along axis None

In [11]:
import numpy

n, m = input().split()
arr = []

for i in range(int(n)):
    arr.append(list(map(int, input().split())))
    
arr = numpy.array(arr)

print(numpy.mean(arr, axis=1))
print(numpy.var(arr, axis=0))
print(numpy.around(numpy.std(arr), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


### 12 - You are given two arrays A and B. Both have dimensions of NxM. Your task is to compute their matrix product.

In [12]:
import numpy

n = int(input())
arr1 = []
arr2 = []

for i in range(n):
    arr1.append(input().split())
    
for i in range(n):
    arr2.append(input().split())
    
arr1 = numpy.array(arr1, int)
arr2 = numpy.array(arr2, int)

print(numpy.dot(arr1, arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


### 13 - You are given two arrays: A and B. Your task is to compute their inner and outer product.

In [13]:
import numpy

arr1 = numpy.array(input().split(), int)
arr2 = numpy.array(input().split(), int)

print(numpy.inner(arr1, arr2))
print(numpy.outer(arr1, arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


### 14 - You are given the coefficients of a polynomial P. Your task is to find the value of P at point x.

In [14]:
import numpy

s = numpy.array(input().split(), float)
print(numpy.polyval(s, float(input())))

1.1 2 3
0
3.0


### 15 - You are given a square matrix A with dimensions NxN. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

In [15]:
import numpy

n = int(input())
arr1 = []

for i in range(n):
    arr1.append(input().split())
    
arr1 = numpy.array(arr1, float)
print(round(numpy.linalg.det(arr1), 2))

2
1.1 1.1
1.1 1.1
0.0
